name: Run Gradle Build
on:
  push:
  workflow_dispatch:
jobs:
  buildGradle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build the project
        run: ./gradlew build
      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/main.html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html
      - name: Post in Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Upload coverage to gh-pages
        uses: actions/deploy-pages@v4 
        with:
          artifact_name: coverage-report
