name: Run Gradle Build
on:
  push:
  workflow_dispatch:
jobs:
  buildGradle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build the project
        run: ./gradlew build
      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/main.html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html
      - name: Post in Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  prepare_site:
    needs: buildGradle
    runs-on: ubuntu-latest
    steps:
      - name: Check out _site directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            _site
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: _site/coverage
      - name: Download pmd report
        uses: actions/download-artifact@v4
        with:
          name: pmd-report
          path: _site/pmd.html      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
    
  pages_deploy:
    needs: prepare_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
